# validate.yml

name: Validate Build
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup npm
        uses: actions/setup-node@v3.0.0

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Install sf jest package and Sa11y library
        run: |
          cd main
          sf force lightning lwc test setup
          npm install -D @sa11y/jest    
          
      - name: Run LWC jest tests
        run: |
          npm run test:unit:coverage > jest_results 2>&1
          cat jest_results
          if [ $(grep "Tests:\s\+.*[0-9]\+\sfailed" jest_results | wc -l) -ne "0" ]; then $(exit 1); fi
          if [ $(grep "Test Suites:\s\+.*[0-9]\+\sfailed" jest_results | wc -l) -eq "0" ]; then $(exit 0); else $(exit 1); fi
